//import './superCalculator/index.js'
import './bankForm/index.js'
//import './test/index.js'
//import './API/index.js';
//import './random/index.js';
//import './sitStair/index.js';
//import './realTime/index.js';
//import './entity/index.js'
//import './block/index.js';
//import './moneybag/index.js';
//import './customEnch/index.js';
//import './health_indicator/index.js';
//import './ignoreBlock/index.js';
//import './BankSystem/index.js';
//import './Guild_Menu/index.js';